"""Community-suggested senior-player careers, canonical club names; reviewed snapshots.

Rumours, youth squads, unverified 2026 claims are NOT auto-imported. Maintain and
verify histories against club announcements. Transfers may become outdated.
"""
PLAYER_HISTORIES = [
('Roberto Carlos', ('Palmeiras','Inter','Real Madrid','Fenerbahçe','Corinthians','Anzhi Makhachkala')),
('Mesut Özil', ('Schalke 04','Werder Bremen','Real Madrid','Arsenal','Fenerbahçe','İstanbul Başakşehir')),
('Nani', ('Sporting CP','Manchester United','Fenerbahçe','Valencia','Orlando City','Venezia')),
('Robin van Persie', ('Feyenoord','Arsenal','Manchester United','Fenerbahçe')),
('Fred', ('Internacional','Shakhtar Donetsk','Manchester United','Fenerbahçe')),
('Nicolas Anelka', ('PSG','Arsenal','Real Madrid','Liverpool','Manchester City','Fenerbahçe','Bolton','Chelsea','Juventus','West Brom')),
('Raul Meireles', ('Boavista','Porto','Liverpool','Chelsea','Fenerbahçe')),
('Edin Džeko', ('Željezničar','Teplice','Wolfsburg','Manchester City','Roma','Inter','Fenerbahçe','Fiorentina','Schalke 04')),
('Diego Ribas', ('Santos','Porto','Werder Bremen','Juventus','Wolfsburg','Atletico Madrid','Fenerbahçe','Flamengo')),
('Mauro Icardi', ('Sampdoria','Inter','PSG','Galatasaray')),
('Victor Osimhen', ('Wolfsburg','Charleroi','Lille','Napoli','Galatasaray')),
('Hakim Ziyech', ('Heerenveen','Twente','Ajax','Chelsea','Galatasaray','Al-Duhail')),
('Dries Mertens', ('AGOVV','Utrecht','PSV','Napoli','Galatasaray')),
('Juan Mata', ('Valencia','Chelsea','Manchester United','Galatasaray','Vissel Kobe')),
('Lucas Torreira', ('Pescara','Sampdoria','Arsenal','Atletico Madrid','Galatasaray')),
('Davinson Sánchez', ('América de Cali','Ajax','Tottenham','Galatasaray')),
('Tanguy Ndombele', ('Amiens','Lyon','Tottenham','Napoli','Galatasaray','Nice')),
('Sergio Oliveira', ('Porto','Paços de Ferreira','Nantes','Roma','Galatasaray','Al-Ittihad')),
('Fernando Muslera', ('Nacional','Lazio','Galatasaray')),
('Felipe Melo', ('Flamengo','Cruzeiro','Mallorca','Almería','Fiorentina','Juventus','Galatasaray','Inter','Palmeiras','Fluminense')),
('Wesley Sneijder', ('Ajax','Real Madrid','Inter','Galatasaray','Nice','Al-Gharafa')),
('Didier Drogba', ('Le Mans','Guingamp','Marseille','Chelsea','Shanghai Shenhua','Galatasaray','Montreal Impact','Phoenix Rising')),
('Ryan Babel', ('Ajax','Liverpool','Hoffenheim','Kasımpaşa','Beşiktaş','Fulham','Galatasaray','Eyüpspor')),
('Cenk Tosun', ('Gaziantepspor','Beşiktaş','Everton','Crystal Palace','Fenerbahçe')),
('Miralem Pjanić', ('Metz','Lyon','Roma','Juventus','Barcelona','Beşiktaş','Sharjah')),
('Wout Weghorst', ('Emmen','Heracles','AZ','Wolfsburg','Burnley','Beşiktaş','Manchester United','Hoffenheim','Ajax')),
('Dele Alli', ('Milton Keynes Dons','Tottenham','Everton','Beşiktaş','Como')),
('Mario Gómez', ('Stuttgart','Bayern Münih','Fiorentina','Beşiktaş','Wolfsburg')),
('Pepe', ('Marítimo','Porto','Real Madrid','Beşiktaş')),
('Vincent Aboubakar', ('Valenciennes','Lorient','Porto','Beşiktaş','Al-Nassr','Hatayspor')),
('Anderson Talisca', ('Bahia','Benfica','Beşiktaş','Guangzhou Evergrande','Al-Nassr','Fenerbahçe')),
('Gedson Fernandes', ('Benfica','Tottenham','Galatasaray','Beşiktaş')),
('Rafa Silva', ('Braga','Benfica','Beşiktaş')),
('Alex Oxlade-Chamberlain', ('Southampton','Arsenal','Liverpool','Beşiktaş')),
('Michy Batshuayi', ('Standard Liège','Marseille','Chelsea','Borussia Dortmund','Valencia','Crystal Palace','Beşiktaş','Fenerbahçe','Galatasaray')),
('N’Golo Kanté', ('Boulogne','Caen','Leicester City','Chelsea','Al-Ittihad')),
('Kerem Aktürkoğlu', ('İstanbulspor','24 Erzincanspor','Galatasaray','Benfica','Fenerbahçe')),
('İlkay Gündoğan', ('Bochum','Nürnberg','Borussia Dortmund','Manchester City','Barcelona','Galatasaray')),
('Leroy Sané', ('Schalke 04','Manchester City','Bayern Münih','Galatasaray')),
('Rafael Leão', ('Sporting CP','Lille','AC Milan','Galatasaray')),
('Mohamed Salah', ('El Mokawloon','Basel','Chelsea','Fiorentina','Roma','Liverpool','Trabzonspor')),
('Marco Asensio', ('Mallorca','Real Madrid','PSG','Fenerbahçe')),
('Milan Škriniar', ('Žilina','Sampdoria','Inter','PSG','Fenerbahçe')),
('Mattéo Guendouzi', ('Lorient','Arsenal','Hertha Berlin','Marseille','Lazio','Fenerbahçe')),
('Wilfried Singo', ('Torino','Monaco','Galatasaray')),
('Gabriel Sara', ('São Paulo','Norwich City','Galatasaray')),
('Ismail Jakobs', ('Köln','Monaco','Galatasaray')),
('Mario Lemina', ('Lorient','Marseille','Juventus','Southampton','Nice','Wolverhampton','Galatasaray')),
('Roland Sallai', ('Puskás Akadémia','Palermo','Freiburg','Galatasaray')),
('Tammy Abraham', ('Chelsea','Bristol City','Swansea','Aston Villa','Roma','AC Milan','Beşiktaş')),
('Wilfred Ndidi', ('Genk','Leicester City','Beşiktaş')),
('Orkun Kökçü', ('Feyenoord','Benfica','Beşiktaş')),
('Gheorghe Hagi', ('Steaua București','Real Madrid','Brescia','Barcelona','Galatasaray')),
('Cláudio Taffarel', ('Internacional','Parma','Reggiana','Atlético Mineiro','Galatasaray')),
('Mario Jardel', ('Grêmio','Vasco da Gama','Porto','Galatasaray','Sporting CP','Bolton')),
('Jay-Jay Okocha', ('Enugu Rangers','Eintracht Frankfurt','Fenerbahçe','PSG','Bolton','Hull City')),
('Pierre van Hooijdonk', ('NAC Breda','Celtic','Nottingham Forest','Vitesse','Feyenoord','Fenerbahçe')),
('Dirk Kuyt', ('Utrecht','Feyenoord','Liverpool','Fenerbahçe')),
('Ricardo Quaresma', ('Sporting CP','Barcelona','Porto','Inter','Chelsea','Beşiktaş','Kasımpaşa')),
('Guti', ('Real Madrid','Beşiktaş')),
('Bobô', ('Corinthians','Beşiktaş','Grêmio','Sydney FC','Kayserispor')),
('Hugo Almeida', ('Porto','Bochum','Werder Bremen','Beşiktaş','Cesena','Hannover 96')),
('Demba Ba', ('Rouen','Mouscron','Hoffenheim','West Ham','Newcastle United','Chelsea','Beşiktaş','Shanghai Shenhua','İstanbul Başakşehir')),
('Kevin-Prince Boateng', ('Hertha Berlin','Tottenham','Portsmouth','Genoa','AC Milan','Schalke 04','Las Palmas','Eintracht Frankfurt','Sassuolo','Barcelona','Fiorentina','Beşiktaş','Monza')),
('Radamel Falcao', ('River Plate','Porto','Atletico Madrid','Monaco','Manchester United','Chelsea','Galatasaray','Rayo Vallecano')),
('Franck Ribéry', ('Boulogne','Metz','Galatasaray','Marseille','Bayern Münih','Fiorentina','Salernitana')),
('Arda Turan', ('Galatasaray','Atletico Madrid','Barcelona','İstanbul Başakşehir')),
('Hamit Altıntop', ('Schalke 04','Bayern Münih','Real Madrid','Galatasaray')),
('Burak Yılmaz', ('Antalyaspor','Beşiktaş','Manisaspor','Fenerbahçe','Trabzonspor','Galatasaray','Lille','Fortuna Sittard')),
('Caner Erkin', ('Manisaspor','CSKA Moskova','Galatasaray','Fenerbahçe','Inter','Beşiktaş','Fatih Karagümrük','İstanbul Başakşehir')),
('Emre Belözoğlu', ('Galatasaray','Inter','Newcastle United','Fenerbahçe','İstanbul Başakşehir')),
('Samuel Eto’o', ('Real Madrid','Mallorca','Barcelona','Inter','Anzhi Makhachkala','Chelsea','Everton','Sampdoria','Antalyaspor','Konyaspor')),
('Lukas Podolski', ('Köln','Bayern Münih','Arsenal','Inter','Galatasaray','Antalyaspor','Górnik Zabrze')),
('Alex de Souza', ('Coritiba','Palmeiras','Cruzeiro','Parma','Fenerbahçe')),
('Elvir Bolić', ('Željezničar','Galatasaray','Fenerbahçe','Rayo Vallecano','İstanbulspor')),
('Diego Lugano', ('Nacional','São Paulo','Fenerbahçe','PSG','Málaga','West Brom','Cerro Porteño')),
('Moussa Sow', ('Rennes','Lille','Fenerbahçe','Al-Ahli','Bursaspor')),
('Luiz Gustavo', ('Hoffenheim','Bayern Münih','Wolfsburg','Marseille','Fenerbahçe','Al-Nassr','São Paulo')),
('Josef de Souza', ('Grêmio','Porto','São Paulo','Fenerbahçe','Al-Ahli','Beşiktaş','Beijing Guoan')),
('André Santos', ('Figueirense','Corinthians','Fenerbahçe','Arsenal','Grêmio','Flamengo')),
('Edu Dracena', ('Guarani','Olympiacos','Cruzeiro','Fenerbahçe','Santos','Palmeiras')),
('Fábio Luciano', ('Corinthians','Internacional','Fenerbahçe','Flamengo','Cruzeiro')),
('Giuliano', ('Internacional','Grêmio','Dnipro','Zenit','Fenerbahçe','Al-Nassr','Corinthians')),
('Leonardo Bonucci', ('Inter','Treviso','Pisa','Bari','Juventus','AC Milan','Union Berlin','Fenerbahçe')),
('Martin Škrtel', ('Ružomberok','Zenit','Liverpool','Fenerbahçe','Aston Villa','İstanbul Başakşehir')),
('Simon Kjær', ('Midtjylland','Palermo','Roma','Wolfsburg','Lille','Fenerbahçe','Sevilla','AC Milan')),
('Max Kruse', ('Werder Bremen','St. Pauli','Freiburg','Borussia Mönchengladbach','Wolfsburg','Fenerbahçe','Union Berlin')),
('Roberto Soldado', ('Real Madrid','Osasuna','Getafe','Valencia','Tottenham','Villarreal','Fenerbahçe','Granada','Levante')),
('Dani Güiza', ('Mallorca','Barcelona','Ciudad de Murcia','Getafe','Fenerbahçe','Cádiz')),
('Mateja Kežman', ('Partizan','PSV','Chelsea','Atletico Madrid','Fenerbahçe','PSG','Zenit')),
('Ariel Ortega', ('River Plate','Valencia','Sampdoria','Parma','Fenerbahçe','Newell’s Old Boys')),
('Kennet Andersson', ('IFK Göteborg','Lille','Caen','Bari','Bologna','Lazio','Fenerbahçe')),
('Toni Schumacher', ('Köln','Schalke 04','Fenerbahçe','Bayern Münih')),
('Stephen Appiah', ('Udinese','Parma','Brescia','Juventus','Fenerbahçe','Bologna','Cesena')),
('Mamadou Niang', ('Troyes','Strasbourg','Marseille','Fenerbahçe','Al-Sadd','Beşiktaş')),
('Kim Min-jae', ('Jeonbuk Hyundai','Beijing Guoan','Fenerbahçe','Napoli','Bayern Münih')),
('Bright Osayi-Samuel', ('Blackpool','QPR','Fenerbahçe','Birmingham City')),
('Attila Szalai', ('Haladás','Apollon Limassol','Fenerbahçe','Hoffenheim','Freiburg')),
('İrfan Can Kahveci', ('Gençlerbirliği','İstanbul Başakşehir','Fenerbahçe')),
('Mert Hakan Yandaş', ('Menemen','Tarsus','Sivasspor','Fenerbahçe')),
('Miha Zajc', ('Olimpija Ljubljana','Empoli','Fenerbahçe','Dinamo Zagreb')),
('Serdar Aziz', ('Bursaspor','Galatasaray','Fenerbahçe')),
('Bruma', ('Sporting CP','Galatasaray','Real Sociedad','PSV','Fenerbahçe','Braga')),
('Sinan Gümüş', ('Stuttgart','Galatasaray','Genoa','Antalyaspor','Fenerbahçe')),
('Garry Rodrigues', ('Levski Sofia','Elazığspor','Galatasaray','Fenerbahçe','Al-Ittihad','Olympiacos')),
('Colin Kazım-Richards', ('Bury','Brighton','Sheffield United','Fenerbahçe','Galatasaray','Olympiacos','Celtic','Coritiba')),
('Stjepan Tomas', ('Dinamo Zagreb','Vicenza','Como','Fenerbahçe','Galatasaray','Rubin Kazan')),
('Fatih Akyel', ('Galatasaray','Mallorca','Fenerbahçe','Bochum','Kasımpaşa')),
('Emre Aşık', ('Fenerbahçe','Ankaragücü','Galatasaray','Beşiktaş')),
('Sergen Yalçın', ('Beşiktaş','Fenerbahçe','Galatasaray','Trabzonspor')),
('Saffet Sancaklı', ('Beşiktaş','Kocaelispor','Galatasaray','Fenerbahçe')),
('Tanju Çolak', ('Samsunspor','Galatasaray','Fenerbahçe','İstanbulspor')),
('Mehmet Topal', ('Galatasaray','Valencia','Fenerbahçe','İstanbul Başakşehir')),
('Olcan Adın', ('Fenerbahçe','Gaziantepspor','Trabzonspor','Galatasaray','Akhisarspor')),
('Haim Revivo', ('Maccabi Haifa','Celta Vigo','Fenerbahçe','Galatasaray')),
('Elvir Baljić', ('Željezničar','Bursaspor','Fenerbahçe','Real Madrid','Galatasaray','İstanbulspor')),
('Atiba Hutchinson', ('Östers','Helsingborg','Kopenhag','PSV','Beşiktaş')),
('Tomáš Sivok', ('Sparta Praha','Udinese','Beşiktaş','Bursaspor')),
('Filip Hološko', ('Slovan Bratislava','Manisaspor','Beşiktaş','Çaykur Rizespor')),
('Daniel Amokachi', ('Club Brugge','Everton','Beşiktaş','İstanbulspor')),
('Óscar Córdoba', ('América de Cali','Boca Juniors','Perugia','Beşiktaş','Antalyaspor')),
('Adriano Correia', ('Coritiba','Sevilla','Barcelona','Beşiktaş')),
('Manuel Fernandes', ('Benfica','Portsmouth','Valencia','Everton','Beşiktaş','Lokomotiv Moskva','Kasımpaşa')),
('Simão Sabrosa', ('Sporting CP','Barcelona','Atletico Madrid','Espanyol','Beşiktaş')),
('José Sosa', ('Estudiantes','Bayern Münih','Napoli','Metalist Kharkiv','Beşiktaş','AC Milan','Trabzonspor','Fenerbahçe')),
('Gary Medel', ('Universidad Católica','Boca Juniors','Sevilla','Cardiff City','Inter','Beşiktaş','Bologna')),
('Álvaro Negredo', ('Real Madrid Castilla','Almería','Sevilla','Manchester City','Valencia','Middlesbrough','Beşiktaş','Cádiz')),
('Ciro Immobile', ('Juventus','Siena','Genoa','Torino','Sevilla','Bordeaux','Lazio','Beşiktaş','Bologna')),
('Domagoj Vida', ('Dinamo Zagreb','Bayer Leverkusen','Dynamo Kyiv','Beşiktaş','AEK Athens')),
('Gökhan Gönül', ('Gençlerbirliği','Fenerbahçe','Beşiktaş','Çaykur Rizespor')),
('Vagner Love', ('Palmeiras','CSKA Moskova','Flamengo','Beşiktaş','Al-Shabab','Kayserispor')),
('Dentinho', ('Corinthians','Shakhtar Donetsk','Beşiktaş','Ceará')),
('Rodrigo Tabata', ('Goiás','Santos','Gaziantepspor','Beşiktaş','Al-Sadd','Al-Rayyan')),
('Ronaldo Guiaro', ('Atlético Mineiro','Benfica','Beşiktaş','Santos')),
('Bülent Korkmaz', ('Galatasaray',)),
('Hakan Şükür', ('Sakaryaspor','Bursaspor','Galatasaray','Torino','Inter','Parma')),
('Arif Erdem', ('Galatasaray','Real Sociedad')),
('Ümit Davala', ('Galatasaray','AC Milan','Inter','Werder Bremen')),
('Hasan Şaş', ('Ankaragücü','Galatasaray')),
('Tugay Kerimoğlu', ('Galatasaray','Rangers','Blackburn Rovers')),
('Okan Buruk', ('Galatasaray','Inter','Beşiktaş','İstanbulspor')),
('Ergün Penbe', ('Gençlerbirliği','Galatasaray')),
('Faryd Mondragón', ('Independiente','Argentinos Juniors','Cerro Porteño','Galatasaray','Köln','Philadelphia Union')),
('Gheorghe Popescu', ('Universitatea Craiova','PSV','Tottenham','Barcelona','Galatasaray','Lecce')),
('Harry Kewell', ('Leeds United','Liverpool','Galatasaray','Melbourne Heart','Al-Gharafa')),
('Nigel de Jong', ('Ajax','Hamburg','Manchester City','AC Milan','Galatasaray','LA Galaxy','Al-Ahli')),
('Jason Denayer', ('Manchester City','Celtic','Galatasaray','Sunderland','Lyon','Al-Fateh')),
('Yuto Nagatomo', ('FC Tokyo','Cesena','Inter','Galatasaray')),
('Sofiane Feghouli', ('Grenoble','Valencia','West Ham','Galatasaray','Al-Sadd','Al-Nassr')),
('Bafetimbi Gomis', ('Saint-Étienne','Lyon','Swansea','Galatasaray','Al-Hilal','Kawasaki Frontale')),
('Ryan Donk', ('AZ','West Brom','Club Brugge','Kasımpaşa','Galatasaray')),
('Henry Onyekuru', ('Eupen','Everton','Anderlecht','Galatasaray','Monaco','Olympiacos','Adana Demirspor')),
('Emre Akbaba', ('Antalyaspor','Alanyaspor','Galatasaray','Adana Demirspor','Eyüpspor')),
('Sacha Boey', ('Rennes','Dijon','Galatasaray','Bayern Münih')),
('Kerem Demirbay', ('Borussia Dortmund','Hamburger SV','Hoffenheim','Bayer Leverkusen','Galatasaray')),
('Wilfried Zaha', ('Crystal Palace','Manchester United','Galatasaray','Lyon','Charlotte FC')),
('Barış Alper Yılmaz', ('Ankara Demirspor','Galatasaray')),
('Abdülkerim Bardakcı', ('Konyaspor','Altınordu','Galatasaray')),
('Kaan Ayhan', ('Schalke 04','Fortuna Düsseldorf','Sassuolo','Galatasaray')),
('Yunus Akgün', ('Galatasaray','Adana Demirspor','Leicester City')),
('Robinho', ('Santos','Real Madrid','Manchester City','AC Milan','Sivasspor','İstanbul Başakşehir')),
('Emmanuel Adebayor', ('Metz','Monaco','Arsenal','Manchester City','Real Madrid','Tottenham','Crystal Palace','İstanbul Başakşehir','Kayserispor')),
('Gervinho', ('Beveren','Le Mans','Lille','Arsenal','Roma','Parma','Trabzonspor')),
('Óscar Cardozo', ('Cerro Porteño','Newell’s Old Boys','Benfica','Trabzonspor','Olympiacos','Libertad')),
('Paul Onuachu', ('Midtjylland','Genk','Southampton','Trabzonspor')),
('Edin Višća', ('Željezničar','İstanbul Başakşehir','Trabzonspor')),
('Anthony Nwakaeme', ('Elazığspor','Trabzonspor','Al-Fayha')),
('Marek Hamšík', ('Slovan Bratislava','Brescia','Napoli','Dalian Professional','Trabzonspor')),
('Caleb Ekuban', ('Chievo Verona','Leeds United','Trabzonspor','Genoa')),
('Umut Bulut', ('Ankaragücü','Trabzonspor','Toulouse','Galatasaray','Kayserispor','Yeni Malatyaspor')),
('Abdülkadir Ömür', ('Trabzonspor','Hull City')),
('Mahmoud Trezeguet', ('Al Ahly','Anderlecht','Kasımpaşa','Aston Villa','Trabzonspor','Al-Rayyan')),
('Okay Yokuşlu', ('Altay','Kayserispor','Trabzonspor','Celta Vigo','West Brom')),
('Yusuf Yazıcı', ('Trabzonspor','Lille','CSKA Moskova')),
('Islam Slimani', ('Sporting CP','Leicester City','Newcastle United','Monaco','Fenerbahçe','Lyon','Anderlecht')),
('Yassine Benzia', ('Lyon','Lille','Fenerbahçe','Dijon','Qarabağ')),
('Max Meyer', ('Schalke 04','Crystal Palace','Fenerbahçe','Midtjylland','Luzern')),
('Mergim Berisha', ('Red Bull Salzburg','Fenerbahçe','Augsburg','Hoffenheim')),
('Vincent Janssen', ('AZ','Tottenham','Fenerbahçe','Monterrey','Antwerp')),
('Jeremain Lens', ('AZ','PSV','Dynamo Kyiv','Sunderland','Beşiktaş','Fatih Karagümrük')),
('Gregory van der Wiel', ('Ajax','PSG','Fenerbahçe','Toronto FC')),
('Eljif Elmas', ('Rabotnički','Fenerbahçe','Napoli','RB Leipzig','Torino')),
('Ferdi Kadıoğlu', ('NEC','Fenerbahçe','Brighton')),
('İrfan Can Eğribayat', ('Adana Demirspor','Fenerbahçe')),
('Luan Peres', ('Santos','Marseille','Fenerbahçe','Flamengo')),
('Miguel Crespo', ('Rio Ave','Paços de Ferreira','Fenerbahçe','İstanbul Başakşehir','Rayo Vallecano')),
('João Pedro', ('Fluminense','Palermo','Watford','Cagliari','Fenerbahçe','Grêmio')),
('Lincoln', ('Grêmio','Flamengo','Fenerbahçe','Hatayspor')),
('Willian Arão', ('Corinthians','Botafogo','Flamengo','Fenerbahçe','Panathinaikos')),
('Gustavo Henrique', ('Santos','Flamengo','Fenerbahçe','Valladolid')),
('Rodrigo Becão', ('Bahia','Udinese','Fenerbahçe')),
('Diego Carlos', ('Estoril','Nantes','Sevilla','Aston Villa','Fenerbahçe')),
('Sofyan Amrabat', ('Utrecht','Feyenoord','Club Brugge','Fiorentina','Manchester United','Fenerbahçe')),
('Vedat Muriqi', ('Teuta','Giresunspor','Gençlerbirliği','Çaykur Rizespor','Fenerbahçe','Lazio','Mallorca')),
]
