"""Additional curated senior first-team histories (no youth squads).

Team-spell data is a maintained sample, not a complete licensed transfer feed.
Notable 2026 update: Gabriel Jesus joined Barcelona; FC Barcelona 2026/27
first-team profile https://www.fcbarcelona.com/en/futbol/primer-equipo/jugadores/19680/---------------gabriel-jesus
"""
EXTRA_HISTORIES = [
    ('Gabriel Jesus', ('Manchester City','Arsenal','Barcelona')),
    ('Luís Figo', ('Barcelona','Real Madrid','Inter')),
    ('Luis Enrique', ('Real Madrid','Barcelona')),
    ('Michael Laudrup', ('Barcelona','Real Madrid','Juventus')),
    ('Bernd Schuster', ('Barcelona','Real Madrid','Atletico Madrid')),
    ('Gheorghe Hagi', ('Real Madrid','Barcelona','Galatasaray')),
    ('Javier Saviola', ('Barcelona','Real Madrid','Benfica')),
    ('Robert Prosinečki', ('Real Madrid','Barcelona','Portsmouth')),
    ('Julen Lopetegui', ('Real Madrid','Barcelona')),
    ('Aleix Vidal', ('Sevilla','Barcelona')),
    ('Sergi Roberto', ('Barcelona',)),
    ('Sergio Busquets', ('Barcelona',)),
    ('Andrés Iniesta', ('Barcelona',)),
    ('Lionel Messi', ('Barcelona','PSG','Inter Miami')),
    ('David Villa', ('Valencia','Barcelona','Atletico Madrid')),
    ('Pedro Rodríguez', ('Barcelona','Chelsea','Roma','Lazio')),
    ('Gerard Piqué', ('Manchester United','Barcelona')),
    ('Ronaldinho', ('PSG','Barcelona','AC Milan')),
    ('Deco', ('Porto','Barcelona','Chelsea')),
    ('Yaya Touré', ('Barcelona','Manchester City')),
    ('Alexander Hleb', ('Arsenal','Barcelona')),
    ('Marc Overmars', ('Arsenal','Barcelona')),
    ('Emmanuel Petit', ('Arsenal','Barcelona','Chelsea')),
    ('Alexandre Song', ('Arsenal','Barcelona','West Ham United')),
    ('Sylvinho', ('Arsenal','Barcelona','Manchester City')),
    ('Denis Suárez', ('Barcelona','Arsenal','Sevilla','Villarreal')),
    ('Neto', ('Valencia','Barcelona','Arsenal')),
    ('Wojciech Szczęsny', ('Arsenal','Roma','Juventus','Barcelona')),
    ('Thomas Vermaelen', ('Arsenal','Barcelona')),
    ('Patrick Vieira', ('AC Milan','Arsenal','Juventus','Inter','Manchester City')),
    ('Emmanuel Adebayor', ('Arsenal','Manchester City','Real Madrid','Tottenham')),
    ('Samir Nasri', ('Arsenal','Manchester City','Sevilla','West Ham United')),
    ('Gaël Clichy', ('Arsenal','Manchester City','Başakşehir FK')),
    ('Bacary Sagna', ('Arsenal','Manchester City')),
    ('Kolo Touré', ('Arsenal','Manchester City','Liverpool')),
    ('David Luiz', ('Benfica','Chelsea','PSG','Arsenal')),
    ('William Gallas', ('Chelsea','Arsenal','Tottenham')),
    ('Laurent Koscielny', ('Arsenal',)),
    ('Petr Čech', ('Chelsea','Arsenal')),
    ('Lassana Diarra', ('Chelsea','Arsenal','Portsmouth','Real Madrid','PSG')),
    ('Ashley Cole', ('Arsenal','Chelsea','Roma')),
    ('Nicolas Pépé', ('Arsenal','Trabzonspor','Villarreal')),
    ('Sead Kolašinac', ('Arsenal','Marseille','Atalanta')),
    ('Héctor Bellerín', ('Arsenal','Barcelona','Sporting CP','Real Betis')),
    ('Calum Chambers', ('Arsenal','Aston Villa')),
    ('Aaron Ramsey', ('Arsenal','Juventus','Rangers','Nice')),
    ('Alexis Mac Allister', ('Brighton','Liverpool')),
    ('Jürgen Klopp', ('Mainz',)),
    ('João Pedro', ('Brighton','Chelsea')),
    ('Kai Havertz', ('Bayer Leverkusen','Chelsea','Arsenal')),
    ('Martin Ødegaard', ('Real Madrid','Arsenal','Real Sociedad')),
    ('Aymeric Laporte', ('Athletic Bilbao','Manchester City','Al Nassr')),
    ('Ferran Torres', ('Valencia','Manchester City','Barcelona')),
    ('Eric García', ('Manchester City','Barcelona','Girona')),
    ('İlkay Gündoğan', ('Borussia Dortmund','Manchester City','Barcelona','Galatasaray')),
    ('Clément Lenglet', ('Sevilla','Barcelona','Tottenham','Atletico Madrid')),
    ('Pierre-Emerick Aubameyang', ('AC Milan','Borussia Dortmund','Arsenal','Barcelona','Chelsea','Marseille')),
    ('Marco Verratti', ('PSG',)),
    ('Zlatan Ibrahimović', ('Ajax','Juventus','Inter','Barcelona','AC Milan','PSG','Manchester United')),
    ('Clarence Seedorf', ('Ajax','Real Madrid','Inter','AC Milan')),
    ('Mario Balotelli', ('Inter','Manchester City','AC Milan','Liverpool','Nice','Marseille','Adana Demirspor')),
    ('Antonio Cassano', ('Roma','Real Madrid','Sampdoria','AC Milan','Inter','Parma')),
    ('Roberto Baggio', ('Juventus','AC Milan','Inter','Bologna')),
    ('Hernán Crespo', ('Parma','Lazio','Inter','Chelsea','AC Milan','Genoa')),
    ('Christian Vieri', ('Juventus','Atletico Madrid','Lazio','Inter','AC Milan','Fiorentina','Atalanta')),
    ('Fernando Llorente', ('Athletic Bilbao','Juventus','Sevilla','Swansea City','Tottenham','Napoli','Udinese')),
    ('Franck Ribéry', ('Galatasaray','Marseille','Bayern Münih','Fiorentina','Salernitana')),
    ('Arjen Robben', ('PSV Eindhoven','Chelsea','Real Madrid','Bayern Münih')),
    ('Xabi Alonso', ('Real Sociedad','Liverpool','Real Madrid','Bayern Münih')),
    ('Toni Kroos', ('Bayern Münih','Bayer Leverkusen','Real Madrid')),
    ('Karim Benzema', ('Lyon','Real Madrid','Al Ittihad')),
    ('Isco', ('Valencia','Málaga','Real Madrid','Sevilla','Real Betis')),
    ('Ezequiel Garay', ('Real Madrid','Benfica','Zenit','Valencia')),
    ('Ángel Correa', ('Atletico Madrid',)),
    ('Mario Mandžukić', ('Bayern Münih','Atletico Madrid','Juventus','AC Milan')),
    ('Álvaro Arbeloa', ('Real Madrid','Liverpool','West Ham United')),
    ('Gerard Deulofeu', ('Barcelona','Everton','AC Milan','Watford','Udinese')),
    ('Ivan Rakitić', ('Schalke','Sevilla','Barcelona')),
    ('André Gomes', ('Benfica','Valencia','Barcelona','Everton','Lille')),
    ('Lucas Digne', ('Lille','PSG','Roma','Barcelona','Everton','Aston Villa')),
    ('Memphis Depay', ('PSV Eindhoven','Manchester United','Lyon','Barcelona','Atletico Madrid')),
    ('Frenkie de Jong', ('Willem II','Ajax','Barcelona')),
    ('Ibrahim Afellay', ('PSV Eindhoven','Barcelona','Schalke','Olympiacos','Stoke City')),
    ('Kevin-Prince Boateng', ('Tottenham','Portsmouth','AC Milan','Schalke','Barcelona','Beşiktaş')),
    ('Martin Braithwaite', ('Middlesbrough','Leganes','Barcelona','Espanyol')),
    ('Bojan Krkić', ('Barcelona','Roma','AC Milan','Ajax','Stoke City','Mainz','Alavés')),
    ('Stefan Savić', ('Manchester City','Fiorentina','Atletico Madrid','Trabzonspor')),
    ('Leonardo Bonucci', ('Inter','Juventus','AC Milan','Union Berlin','Fenerbahçe')),
    ('Dušan Vlahović', ('Fiorentina','Juventus')),
    ('Téji Savanier', ('Nîmes','Montpellier')),
    ('Erik Lamela', ('Roma','Tottenham','Sevilla')),
    ('Bryan Gil', ('Sevilla','Tottenham','Valencia','Girona')),
    ('Sergio Reguilón', ('Real Madrid','Sevilla','Tottenham','Atletico Madrid','Manchester United','Brentford')),
    ('Leandro Trossard', ('Brighton','Arsenal')),
    ('Moisés Caicedo', ('Brighton','Chelsea')),
    ('Joshua Zirkzee', ('Bayern Münih','Parma','Anderlecht','Bologna','Manchester United')),
    ('Dominik Szoboszlai', ('Red Bull Salzburg','RB Leipzig','Liverpool')),
    ('Joško Gvardiol', ('RB Leipzig','Manchester City')),
    ('Benjamin Šeško', ('Red Bull Salzburg','RB Leipzig','Manchester United')),
    ('Dani Olmo', ('Dinamo Zagreb','RB Leipzig','Barcelona')),
    ('Christopher Nkunku', ('PSG','RB Leipzig','Chelsea','AC Milan')),
    ('Florian Wirtz', ('Bayer Leverkusen','Liverpool')),
    ('Randal Kolo Muani', ('Nantes','Eintracht Frankfurt','PSG','Juventus','Tottenham')),
]
