"""New player names supplied in PLAYER_HISTORIES_cleaned.txt (Oct 2026).

Only players absent from the existing footballer database were imported.
Existing footballers and their career spell lists are not overwritten.
Duplicates in the supplied file are merged by Unicode-normalized names.
Source histories are community-supplied, not fully independently verified.
Ömer Şişmanoğlu is supplemented from official TFF registration records.
"""

MISSING_HISTORIES = [
    ('Eusébio', ('Sporting Lourenço Marques', 'Benfica', 'Boston Minutemen', 'Monterrey', 'Toronto Metros-Croatia', 'Beira-Mar')),
    ('Rui Costa', ('Benfica', 'Fiorentina', 'Milan')),
    ('Ricardo Carvalho', ('Leça', 'Vitória Setúbal', 'Porto', 'Chelsea', 'Real Madrid', 'Monaco', 'Shanghai SIPG')),
    ('Bernardo Silva', ('Benfica', 'Monaco', 'Manchester City')),
    ('Diogo Jota', ('Paços de Ferreira', 'Atlético Madrid', 'Porto', 'Wolverhampton', 'Liverpool')),
    ('Raphaël Guerreiro', ('Caen', 'Lorient', 'Borussia Dortmund', 'Bayern Münih')),
    ('William Carvalho', ('Sporting CP', 'Cagliari', 'Real Betis', 'Olympiacos')),
    ('Gelson Martins', ('Sporting CP', 'Atlético Madrid', 'Monaco', 'Olympiacos')),
    ('André Silva', ('Porto', 'Milan', 'Sevilla', 'Eintracht Frankfurt', 'RB Leipzig', 'Real Sociedad')),
    ('Gonçalo Guedes', ('Benfica', 'Paris Saint-Germain', 'Valencia', 'Wolverhampton', 'Villarreal')),
    ('Xavi Hernández', ('Barcelona', 'Al-Sadd')),
    ('Raúl González', ('Real Madrid', 'Schalke 04', 'Al-Sadd', 'New York Cosmos')),
    ('David Silva', ('Valencia', 'Manchester City', 'Real Sociedad')),
    ('Dani Carvajal', ('Real Madrid', 'Bayer Leverkusen')),
    ('Rodri', ('Villarreal', 'Atlético Madrid', 'Manchester City')),
    ('Pedri', ('Las Palmas', 'Barcelona')),
    ('Juanfran', ('Real Madrid', 'Espanyol', 'Osasuna', 'Atlético Madrid', 'São Paulo')),
    ('Saúl Ñíguez', ('Atlético Madrid', 'Chelsea', 'Sevilla', 'Flamengo')),
    ('Dani Parejo', ('Real Madrid', 'Queens Park Rangers', 'Getafe', 'Valencia', 'Villarreal')),
    ('Paco Alcácer', ('Valencia', 'Barcelona', 'Borussia Dortmund', 'Villarreal', 'Sharjah')),
    ('Iago Aspas', ('Celta Vigo', 'Liverpool', 'Sevilla')),
    ('Mikel Merino', ('Osasuna', 'Borussia Dortmund', 'Newcastle', 'Real Sociedad', 'Arsenal')),
    ('César Azpilicueta', ('Osasuna', 'Marseille', 'Chelsea', 'Atlético Madrid', 'Sevilla')),
    ('Nacho Fernández', ('Real Madrid', 'Al-Qadsiah')),
    ('Dani Ceballos', ('Real Betis', 'Real Madrid', 'Arsenal')),
    ('Rodrygo', ('Santos', 'Real Madrid')),
    ('Vinícius Júnior', ('Flamengo', 'Real Madrid')),
    ('Eduardo Camavinga', ('Rennes', 'Real Madrid')),
    ('Aurélien Tchouaméni', ('Bordeaux', 'Monaco', 'Real Madrid')),
    ('Zinedine Zidane', ('Cannes', 'Bordeaux', 'Juventus', 'Real Madrid')),
    ('Michel Platini', ('Nancy', 'Saint-Étienne', 'Juventus')),
    ('Hugo Lloris', ('Nice', 'Lyon', 'Tottenham', 'Los Angeles FC')),
    ('Raphaël Varane', ('Lens', 'Real Madrid', 'Manchester United', 'Como')),
    ('Jules Koundé', ('Bordeaux', 'Sevilla', 'Barcelona')),
    ('Dayot Upamecano', ('Red Bull Salzburg', 'RB Leipzig', 'Bayern Münih')),
    ('William Saliba', ('Saint-Étienne', 'Arsenal')),
    ('Mike Maignan', ('Lille', 'Milan')),
    ('Blaise Matuidi', ('Troyes', 'Saint-Étienne', 'Paris Saint-Germain', 'Juventus', 'Inter Miami')),
    ('Adrien Rabiot', ('Paris Saint-Germain', 'Toulouse', 'Juventus', 'Marseille')),
    ('Moussa Sissoko', ('Toulouse', 'Newcastle', 'Tottenham', 'Watford', 'Nantes')),
    ('Alexandre Lacazette', ('Lyon', 'Arsenal')),
    ('Anthony Martial', ('Lyon', 'Monaco', 'Manchester United', 'Sevilla', 'AEK Athens')),
    ('Kurt Zouma', ('Saint-Étienne', 'Chelsea', 'Stoke City', 'Everton', 'West Ham', 'Al-Orobah')),
    ('Lucas Hernández', ('Atlético Madrid', 'Bayern Münih', 'Paris Saint-Germain')),
    ('Theo Hernández', ('Atlético Madrid', 'Real Madrid', 'Milan')),
    ('Bradley Barcola', ('Lyon', 'Paris Saint-Germain')),
    ('Alessandro Del Piero', ('Padova', 'Juventus', 'Sydney FC', 'Delhi Dynamos')),
    ('Gianluigi Buffon', ('Parma', 'Juventus', 'Paris Saint-Germain')),
    ('Fabio Cannavaro', ('Napoli', 'Parma', 'Inter', 'Juventus', 'Real Madrid', 'Al-Ahli')),
    ('Alessandro Nesta', ('Lazio', 'Milan', 'Montreal Impact', 'Chennaiyin')),
    ('Gianluca Vialli', ('Cremonese', 'Sampdoria', 'Juventus', 'Chelsea')),
    ('Paolo Rossi', ('Juventus', 'Como', 'Vicenza', 'Perugia', 'Milan')),
    ('Marco van Basten', ('Ajax', 'Milan')),
    ('Ruud Gullit', ('Haarlem', 'Feyenoord', 'PSV', 'Milan', 'Sampdoria', 'Chelsea')),
    ('Frank Rijkaard', ('Ajax', 'Sporting CP', 'Zaragoza', 'Milan')),
    ('Andrea Barzagli', ('Rondinella', 'Pistoiese', 'Ascoli', 'Palermo', 'Wolfsburg', 'Juventus')),
    ('Giorgio Chiellini', ('Livorno', 'Fiorentina', 'Juventus', 'Los Angeles FC')),
    ('Nicolò Barella', ('Cagliari', 'Inter')),
    ('Lautaro Martínez', ('Racing Club', 'Inter')),
    ('Lorenzo Insigne', ('Napoli', 'Toronto FC')),
    ('Kalidou Koulibaly', ('Metz', 'Genk', 'Napoli', 'Chelsea', 'Al-Hilal')),
    ('Emerson Palmieri', ('Santos', 'Roma', 'Chelsea', 'Lyon', 'West Ham', 'Marseille')),
    ('Matteo Darmian', ('Milan', 'Palermo', 'Torino', 'Manchester United', 'Parma', 'Inter')),
    ('Stephan El Shaarawy', ('Genoa', 'Milan', 'Monaco', 'Roma', 'Shanghai Shenhua')),
    ('Andrea Belotti', ('Palermo', 'Torino', 'Roma', 'Fiorentina', 'Como')),
    ('Chris Smalling', ('Maidstone United', 'Fulham', 'Manchester United', 'Roma')),
    ('Franz Beckenbauer', ('Bayern Münih', 'New York Cosmos', 'Hamburger SV')),
    ('Gerd Müller', ('Bayern Münih', 'Fort Lauderdale Strikers')),
    ('Lothar Matthäus', ('Borussia Mönchengladbach', 'Bayern Münih', 'Inter', 'Metz')),
    ('Karl-Heinz Rummenigge', ('Bayern Münih', 'Inter', 'Servette')),
    ('Oliver Kahn', ('Karlsruhe', 'Bayern Münih')),
    ('Philipp Lahm', ('Bayern Münih', 'Stuttgart')),
    ('Bastian Schweinsteiger', ('Bayern Münih', 'Manchester United', 'Chicago Fire')),
    ('Manuel Neuer', ('Schalke 04', 'Bayern Münih')),
    ('Joshua Kimmich', ('RB Leipzig', 'Bayern Münih')),
    ('Leon Goretzka', ('Bochum', 'Schalke 04', 'Bayern Münih')),
    ('Jamal Musiala', ('Chelsea', 'Bayern Münih')),
    ('Marco Reus', ('Rot Weiss Ahlen', 'Borussia Mönchengladbach', 'Borussia Dortmund', 'LA Galaxy')),
    ('Sami Khedira', ('Stuttgart', 'Real Madrid', 'Juventus', 'Hertha Berlin')),
    ('Julian Brandt', ('Wolfsburg', 'Bayer Leverkusen', 'Borussia Dortmund')),
    ('Yussuf Poulsen', ('Lyngby', 'RB Leipzig')),
    ('Konrad Laimer', ('Red Bull Salzburg', 'RB Leipzig', 'Bayern Münih')),
    ('Benjamin Pavard', ('Lille', 'Stuttgart', 'Bayern Münih', 'Inter')),
    ('Niklas Süle', ('Hoffenheim', 'Bayern Münih', 'Borussia Dortmund')),
    ('Thilo Kehrer', ('Schalke 04', 'Paris Saint-Germain', 'West Ham', 'Monaco')),
    ('Jonathan Tah', ('Hamburger SV', 'Bayer Leverkusen')),
    ('Robin Gosens', ('Vitesse', 'Heracles', 'Atalanta', 'Inter', 'Union Berlin', 'Fiorentina')),
    ('Kevin Trapp', ('Kaiserslautern', 'Eintracht Frankfurt', 'Paris Saint-Germain')),
    ('Johan Cruyff', ('Ajax', 'Barcelona', 'Los Angeles Aztecs', 'Washington Diplomats', 'Levante', 'Feyenoord')),
    ('Dennis Bergkamp', ('Ajax', 'Inter', 'Arsenal')),
    ('Patrick Kluivert', ('Ajax', 'Milan', 'Barcelona', 'Newcastle', 'Valencia', 'Lille')),
    ('Edgar Davids', ('Ajax', 'Milan', 'Juventus', 'Barcelona', 'Inter', 'Tottenham', 'Crystal Palace')),
    ('Cody Gakpo', ('PSV', 'Liverpool')),
    ('Ryan Gravenberch', ('Ajax', 'Bayern Münih', 'Liverpool')),
    ('Steven Bergwijn', ('PSV', 'Tottenham', 'Ajax', 'Al-Ittihad')),
    ('Donyell Malen', ('Ajax', 'PSV', 'Borussia Dortmund', 'Aston Villa')),
    ('Teun Koopmeiners', ('AZ', 'Atalanta', 'Juventus')),
    ('Jurriën Timber', ('Ajax', 'Arsenal')),
    ('Xavi Simons', ('Barcelona', 'Paris Saint-Germain', 'PSV', 'RB Leipzig', 'Tottenham')),
    ('Bobby Charlton', ('Manchester United', 'Preston North End')),
    ('Bobby Moore', ('West Ham', 'Fulham', 'San Antonio Thunder', 'Seattle Sounders')),
    ('Gary Lineker', ('Leicester City', 'Everton', 'Barcelona', 'Tottenham', 'Nagoya Grampus')),
    ('Alan Shearer', ('Southampton', 'Blackburn Rovers', 'Newcastle United')),
    ('Paul Gascoigne', ('Newcastle United', 'Tottenham', 'Lazio', 'Rangers', 'Middlesbrough', 'Everton')),
    ('Steven Gerrard', ('Liverpool', 'LA Galaxy')),
    ('Frank Lampard', ('West Ham', 'Chelsea', 'Manchester City', 'New York City')),
    ('Wayne Rooney', ('Everton', 'Manchester United', 'DC United', 'Derby County')),
    ('Rio Ferdinand', ('West Ham', 'Leeds United', 'Manchester United', 'QPR')),
    ('John Terry', ('Chelsea', 'Aston Villa')),
    ('Marcus Rashford', ('Manchester United', 'Aston Villa')),
    ('Jude Bellingham', ('Birmingham City', 'Borussia Dortmund', 'Real Madrid')),
    ('Jordan Henderson', ('Sunderland', 'Liverpool', 'Al-Ettifaq', 'Ajax', 'Brentford')),
    ('Jack Grealish', ('Aston Villa', 'Manchester City')),
    ('James Maddison', ('Coventry City', 'Norwich City', 'Leicester City', 'Tottenham')),
    ('Mason Mount', ('Chelsea', 'Vitesse', 'Derby County', 'Manchester United')),
    ('Reece James', ('Chelsea', 'Wigan')),
    ('Ben Chilwell', ('Leicester City', 'Chelsea')),
    ('Conor Gallagher', ('Chelsea', 'Charlton', 'Swansea', 'Crystal Palace', 'Atlético Madrid')),
    ('Noni Madueke', ('PSV', 'Chelsea')),
    ('Mykhailo Mudryk', ('Shakhtar Donetsk', 'Chelsea')),
    ('Enzo Fernández', ('River Plate', 'Benfica', 'Chelsea')),
    ('Nicolas Jackson', ('Villarreal', 'Chelsea')),
    ('Armando Broja', ('Chelsea', 'Vitesse', 'Southampton', 'Everton')),
    ('Callum Hudson-Odoi', ('Chelsea', 'Bayer Leverkusen', 'Nottingham Forest')),
    ('Fikayo Tomori', ('Chelsea', 'Derby County', 'Milan')),
    ('Trevoh Chalobah', ('Chelsea', 'Ipswich', 'Lorient', 'Crystal Palace')),
    ('Levi Colwill', ('Chelsea', 'Huddersfield', 'Brighton')),
    ('Vincent Kompany', ('Anderlecht', 'Hamburger SV', 'Manchester City')),
    ('Jan Vertonghen', ('Ajax', 'Tottenham', 'Benfica', 'Anderlecht')),
    ('Toby Alderweireld', ('Ajax', 'Atlético Madrid', 'Southampton', 'Tottenham', 'Al-Duhail', 'Antwerp')),
    ('Axel Witsel', ('Standard Liège', 'Benfica', 'Zenit', 'Tianjin Quanjian', 'Borussia Dortmund', 'Atlético Madrid')),
    ('Youri Tielemans', ('Anderlecht', 'Monaco', 'Leicester City', 'Aston Villa')),
    ('Jérémy Doku', ('Anderlecht', 'Rennes', 'Manchester City')),
    ('Charles De Ketelaere', ('Club Brugge', 'Milan', 'Atalanta')),
    ('Divock Origi', ('Lille', 'Liverpool', 'Wolfsburg', 'Milan', 'Nottingham Forest')),
    ('Christian Benteke', ('Genk', 'Standard Liège', 'Aston Villa', 'Liverpool', 'Crystal Palace', 'DC United')),
    ('Yannick Carrasco', ('Monaco', 'Atlético Madrid', 'Dalian Professional', 'Al-Shabab')),
    ('Thomas Meunier', ('Club Brugge', 'Paris Saint-Germain', 'Borussia Dortmund', 'Trabzonspor')),
    ('Timothy Castagne', ('Genk', 'Atalanta', 'Leicester City', 'Fulham')),
    ('Amadou Onana', ('Hamburg', 'Lille', 'Everton', 'Aston Villa')),
    ('Arthur Theate', ('Ostende', 'Bologna', 'Rennes', 'Eintracht Frankfurt')),
    ('Henrik Larsson', ('Högaborg', 'Helsingborg', 'Feyenoord', 'Celtic', 'Barcelona', 'Manchester United')),
    ('Peter Schmeichel', ('Hvidovre', 'Brøndby', 'Manchester United', 'Sporting CP', 'Aston Villa', 'Manchester City')),
    ('Brian Laudrup', ('Brøndby', 'Bayer Leverkusen', 'Bayern Münih', 'Fiorentina', 'Milan', 'Rangers', 'Chelsea', 'København')),
    ('Andriy Shevchenko', ('Dynamo Kyiv', 'Milan', 'Chelsea')),
    ('Marcelo Brozović', ('Hrvatski Dragovoljac', 'Lokomotiva', 'Dinamo Zagreb', 'Inter', 'Al-Nassr')),
    ('Tomáš Rosický', ('Sparta Praha', 'Borussia Dortmund', 'Arsenal')),
    ('Pavel Nedvěd', ('Dukla Praha', 'Sparta Praha', 'Lazio', 'Juventus')),
    ('Jan Koller', ('Sparta Praha', 'Anderlecht', 'Borussia Dortmund', 'Monaco', 'Nürnberg', 'Krylia Sovetov')),
    ('Gareth Bale', ('Southampton', 'Tottenham', 'Real Madrid', 'Los Angeles FC')),
    ('George Best', ('Manchester United', 'Jewish Guild', 'Cork Celtic', 'Los Angeles Aztecs', 'Fulham', 'Fort Lauderdale Strikers', 'San Jose Earthquakes', 'Bournemouth')),
    ('Kenny Dalglish', ('Celtic', 'Liverpool')),
    ('Graeme Souness', ('Tottenham', 'Middlesbrough', 'Liverpool', 'Sampdoria', 'Rangers')),
    ('Denis Law', ('Huddersfield Town', 'Manchester City', 'Torino', 'Manchester United')),
    ('Mason Greenwood', ('Manchester United', 'Getafe', 'Marseille')),
    ('Ederson', ('Benfica', 'Rio Ave', 'Manchester City', 'Fenerbahçe')),
    ('Ömer Şişmanoğlu', ('St. Pauli', 'Kayserispor', 'Antalyaspor', 'Beşiktaş', 'Eskişehirspor', 'Konyaspor', 'Göztepe', 'Yeni Malatyaspor', 'Erzurumspor FK', 'Denizlispor', 'Iğdır FK', 'Sakaryaspor', 'Kırıkkale FK', 'Osmaniyespor')),
]