"""Career histories supplied by the game creator on 2026-10-09.
These are user-provided records; they have not all been independently verified.
Preserved separately and merged as additive club histories at runtime.
"""

PLAYER_HISTORIES: list[tuple[str, tuple[str, ...]]] = [
    # === PORTEKİZ ===
    ('Cristiano Ronaldo', ('Sporting CP', 'Manchester United', 'Real Madrid', 'Juventus', 'Al-Nassr')),
    ('Luís Figo', ('Sporting CP', 'Barcelona', 'Real Madrid', 'Inter')),
    ('Eusébio', ('Sporting Lourenço Marques', 'Benfica', 'Boston Minutemen', 'Monterrey', 'Toronto Metros-Croatia', 'Beira-Mar')),
    ('Rui Costa', ('Benfica', 'Fiorentina', 'Milan')),
    ('Deco', ('Benfica', 'Porto', 'Barcelona', 'Chelsea', 'Fluminense')),
    ('Pepe', ('Marítimo', 'Porto', 'Real Madrid', 'Beşiktaş')),
    ('Nani', ('Sporting CP', 'Manchester United', 'Fenerbahçe', 'Valencia', 'Orlando City')),
    ('Ricardo Carvalho', ('Leça', 'Vitória Setúbal', 'Porto', 'Chelsea', 'Real Madrid', 'Monaco', 'Shanghai SIPG')),
    ('João Félix', ('Benfica', 'Atlético Madrid', 'Chelsea', 'Barcelona', 'Milan')),
    ('Bernardo Silva', ('Benfica', 'Monaco', 'Manchester City')),
    ('Bruno Fernandes', ('Novara', 'Udinese', 'Sampdoria', 'Sporting CP', 'Manchester United')),
    ('Rúben Dias', ('Benfica', 'Manchester City')),
    ('Diogo Jota', ('Paços de Ferreira', 'Atlético Madrid', 'Porto', 'Wolverhampton', 'Liverpool')),
    ('Rafael Leão', ('Sporting CP', 'Lille', 'Milan', 'Galatasaray')),
    ('João Cancelo', ('Benfica', 'Valencia', 'Inter', 'Juventus', 'Manchester City', 'Bayern Münih', 'Barcelona', 'Al-Hilal')),
    ('Raphaël Guerreiro', ('Caen', 'Lorient', 'Borussia Dortmund', 'Bayern Münih')),
    ('William Carvalho', ('Sporting CP', 'Cagliari', 'Real Betis', 'Olympiacos')),
    ('Gelson Martins', ('Sporting CP', 'Atlético Madrid', 'Monaco', 'Olympiacos')),
    ('André Silva', ('Porto', 'Milan', 'Sevilla', 'Eintracht Frankfurt', 'RB Leipzig', 'Real Sociedad')),
    ('Gonçalo Guedes', ('Benfica', 'Paris Saint-Germain', 'Valencia', 'Wolverhampton', 'Villarreal')),

    # === İSPANYA ===
    ('Xavi Hernández', ('Barcelona', 'Al-Sadd')),
    ('Andrés Iniesta', ('Barcelona', 'Vissel Kobe', 'Emirates Club')),
    ('Iker Casillas', ('Real Madrid', 'Porto')),
    ('Sergio Ramos', ('Sevilla', 'Real Madrid', 'Paris Saint-Germain')),
    ('Raúl González', ('Real Madrid', 'Schalke 04', 'Al-Sadd', 'New York Cosmos')),
    ('Fernando Torres', ('Atlético Madrid', 'Liverpool', 'Chelsea', 'Milan', 'Sagan Tosu')),
    ('David Villa', ('Sporting Gijón', 'Zaragoza', 'Valencia', 'Barcelona', 'Atlético Madrid', 'Melbourne City', 'Vissel Kobe', 'New York City')),
    ('Gerard Piqué', ('Barcelona', 'Manchester United')),
    ('Sergio Busquets', ('Barcelona', 'Inter Miami')),
    ('Cesc Fàbregas', ('Arsenal', 'Barcelona', 'Chelsea', 'Monaco', 'Como')),
    ('David Silva', ('Valencia', 'Manchester City', 'Real Sociedad', 'Tokyo')),
    ('Juan Mata', ('Real Madrid Castilla', 'Valencia', 'Chelsea', 'Manchester United', 'Galatasaray', 'Vissel Kobe')),
    ('Pedro Rodríguez', ('Barcelona', 'Chelsea', 'Roma', 'Lazio')),
    ('Isco', ('Valencia', 'Málaga', 'Real Madrid', 'Sevilla', 'Real Betis', 'Al-Nassr')),
    ('Antoine Griezmann', ('Real Sociedad', 'Atlético Madrid', 'Barcelona')),
    ('Dani Carvajal', ('Real Madrid', 'Bayer Leverkusen')),
    ('Rodri', ('Villarreal', 'Atlético Madrid', 'Manchester City')),
    ('Pedri', ('Las Palmas', 'Barcelona')),
    ('Ferran Torres', ('Valencia', 'Manchester City', 'Barcelona')),
    ('Álvaro Morata', ('Real Madrid', 'Juventus', 'Chelsea', 'Atlético Madrid', 'Milan', 'Galatasaray')),
    ('Diego Costa', ('Braga', 'Atlético Madrid', 'Chelsea', 'Wolverhampton', 'Botafogo')),
    ('Juanfran', ('Real Madrid', 'Espanyol', 'Osasuna', 'Atlético Madrid', 'São Paulo')),
    ('Saúl Ñíguez', ('Atlético Madrid', 'Chelsea', 'Sevilla', 'Flamengo')),
    ('Marcos Llorente', ('Real Madrid', 'Alavés', 'Atlético Madrid')),
    ('Dani Parejo', ('Real Madrid', 'Queens Park Rangers', 'Getafe', 'Valencia', 'Villarreal')),
    ('Paco Alcácer', ('Valencia', 'Barcelona', 'Borussia Dortmund', 'Villarreal', 'Sharjah')),
    ('Iago Aspas', ('Celta Vigo', 'Liverpool', 'Sevilla')),
    ('Mikel Merino', ('Osasuna', 'Borussia Dortmund', 'Newcastle', 'Real Sociedad', 'Arsenal')),
    ('Aymeric Laporte', ('Athletic Bilbao', 'Manchester City', 'Al-Nassr')),
    ('César Azpilicueta', ('Osasuna', 'Marseille', 'Chelsea', 'Atlético Madrid', 'Sevilla')),
    ('Nacho Fernández', ('Real Madrid', 'Al-Qadsiah')),
    ('Marco Asensio', ('Mallorca', 'Real Madrid', 'Paris Saint-Germain', 'Fenerbahçe')),
    ('Dani Ceballos', ('Real Betis', 'Real Madrid', 'Arsenal')),
    ('Brahim Díaz', ('Manchester City', 'Real Madrid', 'Milan')),
    ('Rodrygo', ('Santos', 'Real Madrid')),
    ('Vinícius Júnior', ('Flamengo', 'Real Madrid')),
    ('Eduardo Camavinga', ('Rennes', 'Real Madrid')),
    ('Aurélien Tchouaméni', ('Bordeaux', 'Monaco', 'Real Madrid')),

    # === FRANSA ===
    ('Zinedine Zidane', ('Cannes', 'Bordeaux', 'Juventus', 'Real Madrid')),
    ('Thierry Henry', ('Monaco', 'Juventus', 'Arsenal', 'Barcelona', 'New York Red Bulls')),
    ('Michel Platini', ('Nancy', 'Saint-Étienne', 'Juventus')),
    ('Franck Ribéry', ('Boulogne', 'Metz', 'Galatasaray', 'Marseille', 'Bayern Münih', 'Fiorentina', 'Salernitana')),
    ('Karim Benzema', ('Lyon', 'Real Madrid', 'Al-Ittihad')),
    ('Hugo Lloris', ('Nice', 'Lyon', 'Tottenham', 'Los Angeles FC')),
    ('Paul Pogba', ('Manchester United', 'Juventus')),
    ('N\'Golo Kanté', ('Boulogne', 'Caen', 'Leicester City', 'Chelsea', 'Al-Ittihad', 'Fenerbahçe')),
    ('Kylian Mbappé', ('Monaco', 'Paris Saint-Germain', 'Real Madrid')),
    ('Olivier Giroud', ('Grenoble', 'Tours', 'Montpellier', 'Arsenal', 'Chelsea', 'Milan', 'Los Angeles FC')),
    ('Raphaël Varane', ('Lens', 'Real Madrid', 'Manchester United', 'Como')),
    ('Kingsley Coman', ('Paris Saint-Germain', 'Juventus', 'Bayern Münih')),
    ('Ousmane Dembélé', ('Rennes', 'Borussia Dortmund', 'Barcelona', 'Paris Saint-Germain')),
    ('Jules Koundé', ('Bordeaux', 'Sevilla', 'Barcelona')),
    ('Dayot Upamecano', ('Red Bull Salzburg', 'RB Leipzig', 'Bayern Münih')),
    ('William Saliba', ('Saint-Étienne', 'Arsenal')),
    ('Mike Maignan', ('Lille', 'Milan')),
    ('Blaise Matuidi', ('Troyes', 'Saint-Étienne', 'Paris Saint-Germain', 'Juventus', 'Inter Miami')),
    ('Adrien Rabiot', ('Paris Saint-Germain', 'Toulouse', 'Juventus', 'Marseille')),
    ('Moussa Sissoko', ('Toulouse', 'Newcastle', 'Tottenham', 'Watford', 'Nantes')),
    ('Alexandre Lacazette', ('Lyon', 'Arsenal')),
    ('Anthony Martial', ('Lyon', 'Monaco', 'Manchester United', 'Sevilla', 'AEK Athens')),
    ('Kurt Zouma', ('Saint-Étienne', 'Chelsea', 'Stoke City', 'Everton', 'West Ham', 'Al-Orobah')),
    ('Lucas Hernández', ('Atlético Madrid', 'Bayern Münih', 'Paris Saint-Germain')),
    ('Theo Hernández', ('Atlético Madrid', 'Real Madrid', 'Milan')),
    ('Christopher Nkunku', ('Paris Saint-Germain', 'RB Leipzig', 'Chelsea')),
    ('Randal Kolo Muani', ('Nantes', 'Eintracht Frankfurt', 'Paris Saint-Germain', 'Juventus')),
    ('Bradley Barcola', ('Lyon', 'Paris Saint-Germain')),

    # === İTALYA ===
    ('Alessandro Del Piero', ('Padova', 'Juventus', 'Sydney FC', 'Delhi Dynamos')),
    ('Andrea Pirlo', ('Brescia', 'Inter', 'Milan', 'Juventus', 'New York City')),
    ('Gianluigi Buffon', ('Parma', 'Juventus', 'Paris Saint-Germain')),
    ('Fabio Cannavaro', ('Napoli', 'Parma', 'Inter', 'Juventus', 'Real Madrid', 'Al-Ahli')),
    ('Alessandro Nesta', ('Lazio', 'Milan', 'Montreal Impact', 'Chennaiyin')),
    ('Roberto Baggio', ('Vicenza', 'Fiorentina', 'Juventus', 'Milan', 'Bologna', 'Inter', 'Brescia')),
    ('Gianluca Vialli', ('Cremonese', 'Sampdoria', 'Juventus', 'Chelsea')),
    ('Paolo Rossi', ('Juventus', 'Como', 'Vicenza', 'Perugia', 'Milan')),
    ('Marco van Basten', ('Ajax', 'Milan')),
    ('Ruud Gullit', ('Haarlem', 'Feyenoord', 'PSV', 'Milan', 'Sampdoria', 'Chelsea')),
    ('Frank Rijkaard', ('Ajax', 'Sporting CP', 'Zaragoza', 'Milan')),
    ('Clarence Seedorf', ('Ajax', 'Sampdoria', 'Real Madrid', 'Inter', 'Milan', 'Botafogo')),
    ('Andrea Barzagli', ('Rondinella', 'Pistoiese', 'Ascoli', 'Palermo', 'Wolfsburg', 'Juventus')),
    ('Giorgio Chiellini', ('Livorno', 'Fiorentina', 'Juventus', 'Los Angeles FC')),
    ('Leonardo Bonucci', ('Inter', 'Treviso', 'Pisa', 'Bari', 'Juventus', 'Milan', 'Union Berlin', 'Fenerbahçe')),
    ('Ciro Immobile', ('Juventus', 'Siena', 'Genoa', 'Torino', 'Sevilla', 'Bordeaux', 'Lazio', 'Beşiktaş')),
    ('Federico Chiesa', ('Fiorentina', 'Juventus', 'Liverpool')),
    ('Nicolò Barella', ('Cagliari', 'Inter')),
    ('Lautaro Martínez', ('Racing Club', 'Inter')),
    ('Sandro Tonali', ('Brescia', 'Milan', 'Newcastle United')),
    ('Lorenzo Insigne', ('Napoli', 'Toronto FC')),
    ('Kalidou Koulibaly', ('Metz', 'Genk', 'Napoli', 'Chelsea', 'Al-Hilal')),
    ('Jorginho', ('Hellas Verona', 'Napoli', 'Chelsea', 'Arsenal')),
    ('Emerson Palmieri', ('Santos', 'Roma', 'Chelsea', 'Lyon', 'West Ham', 'Marseille')),
    ('Matteo Darmian', ('Milan', 'Palermo', 'Torino', 'Manchester United', 'Parma', 'Inter')),
    ('Stephan El Shaarawy', ('Genoa', 'Milan', 'Monaco', 'Roma', 'Shanghai Shenhua')),
    ('Andrea Belotti', ('Palermo', 'Torino', 'Roma', 'Fiorentina', 'Como')),
    ('Tammy Abraham', ('Chelsea', 'Bristol City', 'Swansea', 'Aston Villa', 'Roma', 'Milan', 'Beşiktaş')),
    ('Chris Smalling', ('Maidstone United', 'Fulham', 'Manchester United', 'Roma')),
    ('Romelu Lukaku', ('Anderlecht', 'Chelsea', 'West Brom', 'Everton', 'Manchester United', 'Inter', 'Roma', 'Napoli', 'Fenerbahçe')),

    # === ALMANYA ===
    ('Franz Beckenbauer', ('Bayern Münih', 'New York Cosmos', 'Hamburger SV')),
    ('Gerd Müller', ('Bayern Münih', 'Fort Lauderdale Strikers')),
    ('Lothar Matthäus', ('Borussia Mönchengladbach', 'Bayern Münih', 'Inter', 'Metz')),
    ('Karl-Heinz Rummenigge', ('Bayern Münih', 'Inter', 'Servette')),
    ('Oliver Kahn', ('Karlsruhe', 'Bayern Münih')),
    ('Philipp Lahm', ('Bayern Münih', 'Stuttgart')),
    ('Bastian Schweinsteiger', ('Bayern Münih', 'Manchester United', 'Chicago Fire')),
    ('Manuel Neuer', ('Schalke 04', 'Bayern Münih')),
    ('Toni Kroos', ('Bayern Münih', 'Bayer Leverkusen', 'Real Madrid')),
    ('Mesut Özil', ('Schalke 04', 'Werder Bremen', 'Real Madrid', 'Arsenal', 'Fenerbahçe')),
    ('İlkay Gündoğan', ('Bochum', 'Nürnberg', 'Borussia Dortmund', 'Manchester City', 'Barcelona', 'Galatasaray')),
    ('Leroy Sané', ('Schalke 04', 'Manchester City', 'Bayern Münih', 'Galatasaray')),
    ('Joshua Kimmich', ('RB Leipzig', 'Bayern Münih')),
    ('Leon Goretzka', ('Bochum', 'Schalke 04', 'Bayern Münih')),
    ('Serge Gnabry', ('Arsenal', 'West Brom', 'Werder Bremen', 'Bayern Münih')),
    ('Kai Havertz', ('Bayer Leverkusen', 'Chelsea', 'Arsenal')),
    ('Jamal Musiala', ('Chelsea', 'Bayern Münih')),
    ('Florian Wirtz', ('Köln', 'Bayer Leverkusen')),
    ('Antonio Rüdiger', ('Stuttgart', 'Roma', 'Chelsea', 'Real Madrid')),
    ('Mats Hummels', ('Bayern Münih', 'Borussia Dortmund', 'Roma')),
    ('Mario Götze', ('Borussia Dortmund', 'Bayern Münih', 'PSV', 'Eintracht Frankfurt')),
    ('Marco Reus', ('Rot Weiss Ahlen', 'Borussia Mönchengladbach', 'Borussia Dortmund', 'LA Galaxy')),
    ('Robert Lewandowski', ('Znicz Pruszków', 'Lech Poznań', 'Borussia Dortmund', 'Bayern Münih', 'Barcelona')),
    ('Mario Gómez', ('Stuttgart', 'Bayern Münih', 'Fiorentina', 'Beşiktaş', 'Wolfsburg')),
    ('Sami Khedira', ('Stuttgart', 'Real Madrid', 'Juventus', 'Hertha Berlin')),
    ('Emre Can', ('Bayern Münih', 'Bayer Leverkusen', 'Liverpool', 'Juventus', 'Borussia Dortmund')),
    ('Julian Brandt', ('Wolfsburg', 'Bayer Leverkusen', 'Borussia Dortmund')),
    ('Timo Werner', ('Stuttgart', 'RB Leipzig', 'Chelsea', 'Tottenham', 'Monaco')),
    ('Yussuf Poulsen', ('Lyngby', 'RB Leipzig')),
    ('Konrad Laimer', ('Red Bull Salzburg', 'RB Leipzig', 'Bayern Münih')),
    ('Benjamin Pavard', ('Lille', 'Stuttgart', 'Bayern Münih', 'Inter')),
    ('Niklas Süle', ('Hoffenheim', 'Bayern Münih', 'Borussia Dortmund')),
    ('Thilo Kehrer', ('Schalke 04', 'Paris Saint-Germain', 'West Ham', 'Monaco')),
    ('Jonathan Tah', ('Hamburger SV', 'Bayer Leverkusen')),
    ('Robin Gosens', ('Vitesse', 'Heracles', 'Atalanta', 'Inter', 'Union Berlin', 'Fiorentina')),
    ('Kevin Trapp', ('Kaiserslautern', 'Eintracht Frankfurt', 'Paris Saint-Germain')),

    # === HOLLANDA ===
    ('Johan Cruyff', ('Ajax', 'Barcelona', 'Los Angeles Aztecs', 'Washington Diplomats', 'Levante', 'Feyenoord')),
    ('Marco van Basten', ('Ajax', 'Milan')),
    ('Ruud Gullit', ('Haarlem', 'Feyenoord', 'PSV', 'Milan', 'Sampdoria', 'Chelsea')),
    ('Frank Rijkaard', ('Ajax', 'Sporting CP', 'Zaragoza', 'Milan')),
    ('Dennis Bergkamp', ('Ajax', 'Inter', 'Arsenal')),
    ('Patrick Kluivert', ('Ajax', 'Milan', 'Barcelona', 'Newcastle', 'Valencia', 'Lille')),
    ('Edgar Davids', ('Ajax', 'Milan', 'Juventus', 'Barcelona', 'Inter', 'Tottenham', 'Crystal Palace')),
    ('Clarence Seedorf', ('Ajax', 'Sampdoria', 'Real Madrid', 'Inter', 'Milan', 'Botafogo')),
    ('Wesley Sneijder', ('Ajax', 'Real Madrid', 'Inter', 'Galatasaray', 'Nice', 'Al-Gharafa')),
    ('Arjen Robben', ('Groningen', 'PSV', 'Chelsea', 'Real Madrid', 'Bayern Münih')),
    ('Robin van Persie', ('Feyenoord', 'Arsenal', 'Manchester United', 'Fenerbahçe')),
    ('Memphis Depay', ('PSV', 'Manchester United', 'Lyon', 'Barcelona', 'Atlético Madrid', 'Corinthians')),
    ('Virgil van Dijk', ('Groningen', 'Celtic', 'Southampton', 'Liverpool')),
    ('Frenkie de Jong', ('Willem II', 'Ajax', 'Barcelona')),
    ('Matthijs de Ligt', ('Ajax', 'Juventus', 'Bayern Münih', 'Manchester United')),
    ('Cody Gakpo', ('PSV', 'Liverpool')),
    ('Ryan Gravenberch', ('Ajax', 'Bayern Münih', 'Liverpool')),
    ('Daley Blind', ('Ajax', 'Manchester United', 'Bayern Münih', 'Girona')),
    ('Georginio Wijnaldum', ('Feyenoord', 'PSV', 'Newcastle', 'Liverpool', 'Paris Saint-Germain', 'Roma', 'Al-Ettifaq')),
    ('Steven Bergwijn', ('PSV', 'Tottenham', 'Ajax', 'Al-Ittihad')),
    ('Donyell Malen', ('Ajax', 'PSV', 'Borussia Dortmund', 'Aston Villa')),
    ('Teun Koopmeiners', ('AZ', 'Atalanta', 'Juventus')),
    ('Jurriën Timber', ('Ajax', 'Arsenal')),
    ('Xavi Simons', ('Barcelona', 'Paris Saint-Germain', 'PSV', 'RB Leipzig', 'Tottenham')),

    # === İNGİLTERE ===
    ('Bobby Charlton', ('Manchester United', 'Preston North End')),
    ('Bobby Moore', ('West Ham', 'Fulham', 'San Antonio Thunder', 'Seattle Sounders')),
    ('Gary Lineker', ('Leicester City', 'Everton', 'Barcelona', 'Tottenham', 'Nagoya Grampus')),
    ('Alan Shearer', ('Southampton', 'Blackburn Rovers', 'Newcastle United')),
    ('Paul Gascoigne', ('Newcastle United', 'Tottenham', 'Lazio', 'Rangers', 'Middlesbrough', 'Everton')),
    ('David Beckham', ('Manchester United', 'Preston North End', 'Real Madrid', 'LA Galaxy', 'Milan', 'Paris Saint-Germain')),
    ('Steven Gerrard', ('Liverpool', 'LA Galaxy')),
    ('Frank Lampard', ('West Ham', 'Chelsea', 'Manchester City', 'New York City')),
    ('Wayne Rooney', ('Everton', 'Manchester United', 'DC United', 'Derby County')),
    ('Rio Ferdinand', ('West Ham', 'Leeds United', 'Manchester United', 'QPR')),
    ('John Terry', ('Chelsea', 'Aston Villa')),
    ('Ashley Cole', ('Arsenal', 'Chelsea', 'Roma', 'LA Galaxy', 'Derby County')),
    ('Harry Kane', ('Tottenham', 'Leyton Orient', 'Millwall', 'Norwich', 'Leicester', 'Bayern Münih')),
    ('Raheem Sterling', ('Liverpool', 'Manchester City', 'Chelsea', 'Arsenal')),
    ('Marcus Rashford', ('Manchester United', 'Aston Villa')),
    ('Jude Bellingham', ('Birmingham City', 'Borussia Dortmund', 'Real Madrid')),
    ('Declan Rice', ('West Ham', 'Arsenal')),
    ('Kyle Walker', ('Sheffield United', 'Tottenham', 'Manchester City')),
    ('Jordan Henderson', ('Sunderland', 'Liverpool', 'Al-Ettifaq', 'Ajax', 'Brentford')),
    ('Jack Grealish', ('Aston Villa', 'Manchester City')),
    ('James Maddison', ('Coventry City', 'Norwich City', 'Leicester City', 'Tottenham')),
    ('Mason Mount', ('Chelsea', 'Vitesse', 'Derby County', 'Manchester United')),
    ('Reece James', ('Chelsea', 'Wigan')),
    ('Ben Chilwell', ('Leicester City', 'Chelsea')),
    ('Conor Gallagher', ('Chelsea', 'Charlton', 'Swansea', 'Crystal Palace', 'Atlético Madrid')),
    ('Cole Palmer', ('Manchester City', 'Chelsea')),
    ('Noni Madueke', ('PSV', 'Chelsea')),
    ('Mykhailo Mudryk', ('Shakhtar Donetsk', 'Chelsea')),
    ('Moises Caicedo', ('Independiente del Valle', 'Brighton', 'Chelsea')),
    ('Enzo Fernández', ('River Plate', 'Benfica', 'Chelsea')),
    ('Nicolas Jackson', ('Villarreal', 'Chelsea')),
    ('Armando Broja', ('Chelsea', 'Vitesse', 'Southampton', 'Everton')),
    ('Callum Hudson-Odoi', ('Chelsea', 'Bayer Leverkusen', 'Nottingham Forest')),
    ('Fikayo Tomori', ('Chelsea', 'Derby County', 'Milan')),
    ('Trevoh Chalobah', ('Chelsea', 'Ipswich', 'Lorient', 'Crystal Palace')),
    ('Levi Colwill', ('Chelsea', 'Huddersfield', 'Brighton')),

    # === BELÇİKA ===
    ('Kevin De Bruyne', ('Genk', 'Chelsea', 'Werder Bremen', 'Wolfsburg', 'Manchester City')),
    ('Eden Hazard', ('Lille', 'Chelsea', 'Real Madrid')),
    ('Thibaut Courtois', ('Genk', 'Atlético Madrid', 'Chelsea', 'Real Madrid')),
    ('Vincent Kompany', ('Anderlecht', 'Hamburger SV', 'Manchester City')),
    ('Jan Vertonghen', ('Ajax', 'Tottenham', 'Benfica', 'Anderlecht')),
    ('Toby Alderweireld', ('Ajax', 'Atlético Madrid', 'Southampton', 'Tottenham', 'Al-Duhail', 'Antwerp')),
    ('Axel Witsel', ('Standard Liège', 'Benfica', 'Zenit', 'Tianjin Quanjian', 'Borussia Dortmund', 'Atlético Madrid')),
    ('Youri Tielemans', ('Anderlecht', 'Monaco', 'Leicester City', 'Aston Villa')),
    ('Jérémy Doku', ('Anderlecht', 'Rennes', 'Manchester City')),
    ('Charles De Ketelaere', ('Club Brugge', 'Milan', 'Atalanta')),
    ('Leandro Trossard', ('Genk', 'Brighton', 'Arsenal', 'Beşiktaş')),
    ('Michy Batshuayi', ('Standard Liège', 'Marseille', 'Chelsea', 'Borussia Dortmund', 'Valencia', 'Crystal Palace', 'Beşiktaş', 'Fenerbahçe', 'Galatasaray', 'Abha')),
    ('Divock Origi', ('Lille', 'Liverpool', 'Wolfsburg', 'Milan', 'Nottingham Forest')),
    ('Christian Benteke', ('Genk', 'Standard Liège', 'Aston Villa', 'Liverpool', 'Crystal Palace', 'DC United')),
    ('Yannick Carrasco', ('Monaco', 'Atlético Madrid', 'Dalian Professional', 'Al-Shabab')),
    ('Thomas Meunier', ('Club Brugge', 'Paris Saint-Germain', 'Borussia Dortmund', 'Trabzonspor')),
    ('Timothy Castagne', ('Genk', 'Atalanta', 'Leicester City', 'Fulham')),
    ('Amadou Onana', ('Hamburg', 'Lille', 'Everton', 'Aston Villa')),
    ('Arthur Theate', ('Ostende', 'Bologna', 'Rennes', 'Eintracht Frankfurt')),

    # === DİĞER AVRUPA + TÜRKİYE BAĞLANTILI ===
    ('Zlatan Ibrahimović', ('Malmö FF', 'Ajax', 'Juventus', 'Inter', 'Barcelona', 'Milan', 'Paris Saint-Germain', 'Manchester United', 'LA Galaxy')),
    ('Henrik Larsson', ('Högaborg', 'Helsingborg', 'Feyenoord', 'Celtic', 'Barcelona', 'Manchester United')),
    ('Peter Schmeichel', ('Hvidovre', 'Brøndby', 'Manchester United', 'Sporting CP', 'Aston Villa', 'Manchester City')),
    ('Michael Laudrup', ('Brøndby', 'Lazio', 'Juventus', 'Barcelona', 'Real Madrid', 'Vissel Kobe', 'Ajax')),
    ('Brian Laudrup', ('Brøndby', 'Bayer Leverkusen', 'Bayern Münih', 'Fiorentina', 'Milan', 'Rangers', 'Chelsea', 'København')),
    ('Andriy Shevchenko', ('Dynamo Kyiv', 'Milan', 'Chelsea')),
    ('Gheorghe Hagi', ('Steaua București', 'Real Madrid', 'Brescia', 'Barcelona', 'Galatasaray')),
    ('Luka Modrić', ('Dinamo Zagreb', 'Tottenham', 'Real Madrid')),
    ('Ivan Rakitić', ('Basel', 'Schalke 04', 'Sevilla', 'Barcelona', 'Al-Shabab')),
    ('Marcelo Brozović', ('Hrvatski Dragovoljac', 'Lokomotiva', 'Dinamo Zagreb', 'Inter', 'Al-Nassr')),
    ('Erling Haaland', ('Bryne', 'Molde', 'Red Bull Salzburg', 'Borussia Dortmund', 'Manchester City')),
    ('Martin Ødegaard', ('Strømsgodset', 'Real Madrid', 'Heerenveen', 'Vitesse', 'Real Sociedad', 'Arsenal')),
    ('Victor Osimhen', ('Wolfsburg', 'Charleroi', 'Lille', 'Napoli', 'Galatasaray')),
    ('Mohamed Salah', ('El Mokawloon', 'Basel', 'Chelsea', 'Fiorentina', 'Roma', 'Liverpool', 'Trabzonspor')),
    ('Sadio Mané', ('Metz', 'Red Bull Salzburg', 'Southampton', 'Liverpool', 'Bayern Münih', 'Al-Nassr')),
    ('Wojciech Szczęsny', ('Arsenal', 'Brentford', 'Roma', 'Juventus', 'Barcelona')),
    ('Petr Čech', ('Chmel Blšany', 'Sparta Praha', 'Rennes', 'Chelsea', 'Arsenal')),
    ('Tomáš Rosický', ('Sparta Praha', 'Borussia Dortmund', 'Arsenal')),
    ('Pavel Nedvěd', ('Dukla Praha', 'Sparta Praha', 'Lazio', 'Juventus')),
    ('Jan Koller', ('Sparta Praha', 'Anderlecht', 'Borussia Dortmund', 'Monaco', 'Nürnberg', 'Krylia Sovetov')),
    ('Gareth Bale', ('Southampton', 'Tottenham', 'Real Madrid', 'Los Angeles FC')),
    ('Aaron Ramsey', ('Cardiff City', 'Arsenal', 'Juventus', 'Rangers', 'Nice')),
    ('George Best', ('Manchester United', 'Jewish Guild', 'Cork Celtic', 'Los Angeles Aztecs', 'Fulham', 'Fort Lauderdale Strikers', 'San Jose Earthquakes', 'Bournemouth')),
    ('Kenny Dalglish', ('Celtic', 'Liverpool')),
    ('Graeme Souness', ('Tottenham', 'Middlesbrough', 'Liverpool', 'Sampdoria', 'Rangers')),
    ('Denis Law', ('Huddersfield Town', 'Manchester City', 'Torino', 'Manchester United')),
    ('Roberto Carlos', ('Palmeiras', 'Inter', 'Real Madrid', 'Fenerbahçe', 'Corinthians', 'Anzhi')),
    ('Edin Džeko', ('Željezničar', 'Teplice', 'Wolfsburg', 'Manchester City', 'Roma', 'Inter', 'Fenerbahçe', 'Schalke 04')),
    ('Mauro Icardi', ('Sampdoria', 'Inter', 'Paris Saint-Germain', 'Galatasaray')),
    ('Didier Drogba', ('Le Mans', 'Guingamp', 'Marseille', 'Chelsea', 'Shanghai Shenhua', 'Galatasaray')),
    ('Radamel Falcao', ('River Plate', 'Porto', 'Atlético Madrid', 'Monaco', 'Manchester United', 'Chelsea', 'Galatasaray')),
    ('Samuel Eto\'o', ('Real Madrid', 'Mallorca', 'Barcelona', 'Inter', 'Anzhi', 'Chelsea', 'Everton', 'Antalyaspor', 'Konyaspor')),
    ('Alex de Souza', ('Coritiba', 'Palmeiras', 'Cruzeiro', 'Parma', 'Fenerbahçe')),
    ('Fernando Muslera', ('Nacional', 'Lazio', 'Galatasaray')),
    ('Kerem Aktürkoğlu', ('İstanbulspor', 'Galatasaray', 'Benfica', 'Fenerbahçe')),
    ('Mason Greenwood', ('Manchester United', 'Getafe', 'Marseille', 'Fenerbahçe')),
    ('Ederson', ('Benfica', 'Rio Ave', 'Manchester City', 'Fenerbahçe')),
    ('Dušan Vlahović', ('Partizan', 'Fiorentina', 'Juventus', 'Beşiktaş')),
    ('Orkun Kökçü', ('Feyenoord', 'Benfica', 'Beşiktaş')),
    ('Dušan Tadić', ('Vojvodina', 'Groningen', 'Twente', 'Southampton', 'Ajax', 'Fenerbahçe')),
    ('Milan Škriniar', ('Žilina', 'Sampdoria', 'Inter', 'Paris Saint-Germain', 'Fenerbahçe')),
    ('Hakim Ziyech', ('Heerenveen', 'Twente', 'Ajax', 'Chelsea', 'Galatasaray', 'Al-Duhail')),
    ('Dries Mertens', ('AGOVV', 'Utrecht', 'PSV', 'Napoli', 'Galatasaray')),
    ('Lucas Torreira', ('Peñarol', 'Pescara', 'Sampdoria', 'Arsenal', 'Atlético Madrid', 'Galatasaray')),
    ('Davinson Sánchez', ('América de Cali', 'Ajax', 'Tottenham', 'Galatasaray')),
    ('Wilfried Zaha', ('Crystal Palace', 'Manchester United', 'Galatasaray', 'Lyon', 'Charlotte FC')),
    ('Ryan Babel', ('Ajax', 'Liverpool', 'Hoffenheim', 'Kasımpaşa', 'Beşiktaş', 'Fulham', 'Galatasaray')),
    ('Vincent Aboubakar', ('Valenciennes', 'Lorient', 'Porto', 'Beşiktaş', 'Al-Nassr')),
    ('Anderson Talisca', ('Bahia', 'Benfica', 'Beşiktaş', 'Guangzhou Evergrande', 'Al-Nassr', 'Fenerbahçe')),
    ('Gedson Fernandes', ('Benfica', 'Tottenham', 'Galatasaray', 'Beşiktaş')),
    ('Rafa Silva', ('Braga', 'Benfica', 'Beşiktaş')),
    ('Cenk Tosun', ('Gaziantepspor', 'Beşiktaş', 'Everton', 'Crystal Palace', 'Fenerbahçe')),
    ('Miralem Pjanić', ('Metz', 'Lyon', 'Roma', 'Juventus', 'Barcelona', 'Beşiktaş', 'Sharjah')),
    ('Wout Weghorst', ('Emmen', 'Heracles', 'AZ', 'Wolfsburg', 'Burnley', 'Beşiktaş', 'Manchester United', 'Hoffenheim')),
    ('Dele Alli', ('Milton Keynes Dons', 'Tottenham', 'Everton', 'Beşiktaş', 'Como')),
    ('Alex Oxlade-Chamberlain', ('Southampton', 'Arsenal', 'Liverpool', 'Beşiktaş')),
]
