plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ortakfutbolcu.game'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ortakfutbolcu.game'
        minSdk 24
        targetSdk 35
        versionCode 7
        versionName '0.4.3'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
